### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by wordpad25** [SirVoRaK/chess#1]
Trying to launch the application locally, it requires a mysql database. 
Is there a scheme provided somewhere?

**Comment by rodolfoinfantini** [comment]
Hey!
The file [modules/mysql.js](https://github.com/SirVoRaK/chess/blob/main/modules/mysql.js) creates the tables automatically.
You just need to provide the env vars for the connection in your .env file:
![image](https://user-images.githubusercontent.com/76462264/173274621-912ac939-382a-4989-8e2b-91927fd9761e.png)
MYSQL_HOST, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DB
