### ISSUE TITLE
Your thing isn't working

### ISSUE THREAD

**Issue by ConnorLattimore** [SirVoRaK/chess#2]
I love this project but I was wondering if you could tell me how I could easily run it on my own?

**Comment by HockeyGamr** [comment]
Or maybe just tell me how I could get it working again. This project is so good!

**Comment by rodolfoinfantini** [comment]
Sorry for the delay!
I just updated the repo with some fixes.
Now it works.
You need node 16 to run it, any newer version won´t work because of the stockfish.

**Comment by rodolfoinfantini** [comment]
And you will need some environment vars:

            PORT: xxxx
            MYSQL_HOST: xxxx
            MYSQL_USER: xxxx
            MYSQL_PASSWORD: xxxx
            MYSQL_DB: xxxx
            EMAIL_USER: xxxx@outlook.com (it must be outlook)
            EMAIL_PASS: xxxxx
