### ISSUE TITLE
Online Game is not working

### ISSUE THREAD

**Issue by GMClaud** [SirVoRaK/chess#4]
When creating the online game, after accessing the link, after white moves, black cannot see white's move.
Communication between the 2 boards works. (if one board closes the game, the other can see that).

**Comment by rodolfoinfantini** [comment]
Are you running it locally or trying at the website? [chess.rodolfoi.tech](https://chess.rodolfoi.tech)
I actually had this problem when I went back to this project, it was the NodeJs version, it MUST be 16.

**Comment by GMClaud** [comment]
Hi. It works. It was an issue with the socket.io

**Comment by rodolfoinfantini** [comment]
Nice!
Good to read that it is working for someone else.
