### ISSUE TITLE
Localhost

### ISSUE THREAD

**Issue by PedroLobregati** [SirVoRaK/chess#7]
Sabe me dizer por que só consigo criar um jogo via localhost na porta 3000? Nem com o ip privado da minha máquina carrega a partida, na verdade observei que há algum problema no mysql mas procurei em tudo e não achei nada. Gostaria de saber para fins acadêmicos, estou usando o docker

**Comment by rodolfoinfantini** [comment]
Você consegue passar mais informações? Aqui eu estou rodando em outra maquina inclusive com dominio e está funcionando.
Lembre-se que o node precisa estar na versão 14, qualquer mais nova não consegue rodar o stockfish.
O site carrega acessando o ip interno de outra maquina?

**Comment by PedroLobregati** [comment]
Primeiro eu rodei ele normalmente (estou usando docker) em minha máquina via localhost, isso foi rápido e funcionou tudo certo. Aí com uma máquina virtual fiz a mesma coisa pra deixar rodando publicamente e depois vir com o domínio. E ao testar colocando o IP dessa máquina virtual como domínio na porta 3000 até entra na aplicação, consigo mexer nas configurações aparece o layout e tudo mais. Porém quando eu crio um jogo contra a máquina ou qualquer outra forma não carrega, fica eternamente carregando. Então pra testar rodei novamente na minha máquina e usei meu IP privado e até assim deu a mesma coisa, ou seja, somente via localhost consigo jogar de fato. Sobre a versão do Node não seria a 16?

**Comment by rodolfoinfantini** [comment]
Isso versão 16, escrevi errado ali.
Você consegue ver os logs do servidor na outra maquina?
E do navegador, aparece algum erro no console?

**Comment by rodolfoinfantini** [comment]
Acabei de reproduzir o problema, vou tentar resolver!

**Comment by rodolfoinfantini** [comment]
O problema está no SharedArrayBuffer que o stockfish usa, os navegadores bloqueiam o uso dele em HTTP, funciona apenas em HTTPs.
O único endereço que funciona em HTTP é localhost.
Não tem o que fazer, ele vai funcionar se você colocar um domínio + HTTPs.
Mais informações: [https://stackoverflow.com/questions/74623993/sharedarraybuffer-is-not-defined-error-in-cloud-server-but-working-in-localhos](https://stackoverflow.com/questions/74623993/sharedarraybuffer-is-not-defined-error-in-cloud-server-but-working-in-localhos)

**Comment by PedroLobregati** [comment]
Vou tentar amigo, assim que eu fizer isso coloco aqui se funcionou, obrigado

**Comment by PedroLobregati** [comment]
Me diz uma coisa, se eu quiser adicionar o HTTPs vai precisar alterar alguma coisa no código?

**Comment by rodolfoinfantini** [comment]
Depende de como vc vai fazer isso, eu utilizei o cloudflare tunnel que faz proxy reverso até meu servidor e que ja faz tudo relacionado com HTTPs.
Agora se for fazer manualmente vai precisar editar o arquivo [server.js](https://github.com/rodolfoinfantini/chess/blob/main/server.js). Ele é um servidor express, então são os passos para o express (nunca cheguei a fazer desta forma, então não sei muito bem como ajudar).
Esse link pode ajudar: [https://stackoverflow.com/questions/11744975/enabling-https-on-express-js](https://stackoverflow.com/questions/11744975/enabling-https-on-express-js)

**Comment by PedroLobregati** [comment]
Estou usando o CloudFlare também, e o domínio já foi verificado certinho, mas ainda não deu certo, dá um erro 521 ao tentar acessar o site. Queria eliminar também a necessidade de especificar a porta, ele já faz isso automaticamente? Você chegou a mexer alguma coisa na configuração do DNS no CloudFlare?

**Comment by rodolfoinfantini** [comment]
Na verdade eu não usei as configs padrões para dominio da cloud flare, usei um serviço chamado tunnels.
Basicamente você inicia um container da cloudflare no servidor que esta rodando a aplicação.
No dashboard vc consegue configurar para seu dominio redirecionar para algum outro lugar, nesse caso http://localhost:3000.
Não vou lembrar agora os passos exatos que eu usei, mas assisti esse vídeo na época que eu configurei:
[https://youtu.be/ey4u7OUAF3c](https://youtu.be/ey4u7OUAF3c)

**Comment by PedroLobregati** [comment]
Funcionou amigo, muitíssimo obrigado!
